In [145]:
# import pandas as pd
import numpy as np
# import io
# import statsmodels.formula.api as smf
# import scipy.stats as stats
import re

In [146]:
data_str = '''exper                        0.037***          
                              (0.006)          
                                               
I(exper2)                    -0.001***         
                             (0.0001)          
                                               
female                       -0.363***         
                              (0.040)          
                                               
married                      0.144***          
                              (0.045)          
                                               
smsa                         0.273***          
                              (0.044)          
                                               
Constant                     1.250***          
                              (0.061)'''

In [147]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_data = re.findall(r'([-+]?\d+.\d+)',data_str)
digital_data

['0.037',
 '0.006',
 '-0.001',
 '0.0001',
 '-0.363',
 '0.040',
 '0.144',
 '0.045',
 '0.273',
 '0.044',
 '1.250',
 '0.061']

In [148]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 8 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
arr = np.reshape(digital_data,(6,2))
# arr = np.delete(arr, 2, 0)
# arr = np.delete(arr, 4, 0)
# arr[:, 0]
arr = arr[:, 0]
arr

array(['0.037', '-0.001', '-0.363', '0.144', '0.273', '1.250'],
      dtype='<U6')

In [149]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''  exper female married smsa
                ---------------------------
                1   5     1       1     1  
                2  26     0       0     1  
                3  38     1       1     0  '''

In [150]:
# Создадим список из чисел, содержащихся в строке. 
# ppl_list -- список, который будет состоять из подстрок, каждая из которых удовлетворяет определенному шаблону символов
# ppl_lst = re.findall(r'([-+]?\d+.\d+|[-+]?\d+)',ppl_string)
ppl_lst = re.findall(r'(\d+)',ppl_string)
ppl_lst

['1', '5', '1', '1', '1', '2', '26', '0', '0', '1', '3', '38', '1', '1', '0']

In [151]:
ppl = np.reshape(ppl_lst,(3,5))
ppl

array([['1', '5', '1', '1', '1'],
       ['2', '26', '0', '0', '1'],
       ['3', '38', '1', '1', '0']], dtype='<U2')

In [152]:
# Теперь необходимо добавить столбец из единиц для того,
#  чтобы совпадало количество столбцов в матрице с количестом элементов 
ppl = np.delete(ppl,0,1)
ppl = np.c_[ppl,np.ones(3)]
# X = np.c_[X,np.ones(3)]
# X = np.insert (X, 3 , np.ones(3), axis= 1 )
ppl

array([['5', '1', '1', '1', '1.0'],
       ['26', '0', '0', '1', '1.0'],
       ['38', '1', '1', '0', '1.0']], dtype='<U32')

In [153]:
ppl.shape

(3, 5)

In [154]:
arr.shape

(6,)

In [155]:
arr

array(['0.037', '-0.001', '-0.363', '0.144', '0.273', '1.250'],
      dtype='<U6')

In [156]:
arr = arr.astype(float)
ppl =ppl.astype(float)
ppl = np.insert(ppl, 1 , ppl[:,0]**2, axis= 1)
ppl

array([[5.000e+00, 2.500e+01, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [2.600e+01, 6.760e+02, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00],
       [3.800e+01, 1.444e+03, 1.000e+00, 1.000e+00, 0.000e+00, 1.000e+00]])

In [157]:
print('arr')
print(arr.round(2))
print('ppl')
print(ppl.round(2))

print((ppl@arr).round(2))
print(np.exp((ppl@arr)).round(2))

arr
[ 0.04 -0.   -0.36  0.14  0.27  1.25]
ppl
[[5.000e+00 2.500e+01 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [2.600e+01 6.760e+02 0.000e+00 0.000e+00 1.000e+00 1.000e+00]
 [3.800e+01 1.444e+03 1.000e+00 1.000e+00 0.000e+00 1.000e+00]]
[1.46 1.81 0.99]
[4.32 6.1  2.7 ]
