In [1446]:
# import pandas as pd
import numpy as np
# import io
import statsmodels.formula.api as smf
import statsmodels.api as sm
# import scipy.stats as stats
import re

In [1447]:
data_str = '''log(capital)                 0.208***          
                              (0.017)          
                                               
log(labour)                  0.715***          
                              (0.023)          
                                               
Constant                     -1.711***         
                              (0.097)'''

In [1448]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_data = re.findall(r'([-+]?\d+.\d+)',data_str)
digital_data

['0.208', '0.017', '0.715', '0.023', '-1.711', '0.097']

In [1449]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 8 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
arr = np.reshape(digital_data,(3,2))
# Удаляем последнюю строчку (она нам не понадобится)
# arr = np.delete(arr, 2, 0)
# Убираем последний столбец, он тоже не нужен
arr = arr[:, 0]
# Переводим строки в вещественные числа
arr = arr.astype(float)
# arr = np.log(arr)
# arr = np.exp(arr)
arr

array([ 0.208,  0.715, -1.711])

In [1450]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''capital labour
                ----------------
                1  2.970    85  
                2  10.450    60  
                3  3.850   105  '''

In [1451]:
# Создадим список из чисел, содержащихся в строке. 
# ppl_list -- список, который будет состоять из подстрок, каждая из которых удовлетворяет определенному шаблону символов
# ppl_lst = re.findall(r'([-+]?\d+.\d+|[-+]?\d+)',ppl_string)
ppl_lst = re.findall(r'(\d+.\d+|\d+)',ppl_string)
ppl_lst

['1', '2.970', '85', '2', '10.450', '60', '3', '3.850', '105']

In [1452]:
ppl = np.reshape(ppl_lst,(3,3))
ppl

array([['1', '2.970', '85'],
       ['2', '10.450', '60'],
       ['3', '3.850', '105']], dtype='<U6')

In [1453]:
# Теперь необходимо добавить столбец из единиц для того,
#  чтобы совпадало количество столбцов в матрице с количестом элементов 
ppl = np.delete(ppl,0,1)
ppl = np.c_[ppl,np.ones(3)]
# X = np.c_[X,np.ones(3)]
# X = np.insert (X, 3 , np.ones(3), axis= 1 )
ppl

array([['2.970', '85', '1.0'],
       ['10.450', '60', '1.0'],
       ['3.850', '105', '1.0']], dtype='<U32')

In [1454]:
ppl.shape

(3, 3)

In [1455]:
arr.shape

(3,)

In [1456]:
# arr = arr.astype(float)
ppl =ppl.astype(float)
# ppl = np.insert(ppl, 1 , ppl[:,0]**2, axis= 1)
ppl

array([[  2.97,  85.  ,   1.  ],
       [ 10.45,  60.  ,   1.  ],
       [  3.85, 105.  ,   1.  ]])

In [1457]:
ppl = np.log(ppl)
# arr = np.exp(arr)

In [1458]:
print('arr')
print(arr)
print('ppl')
print(ppl)
# res = ((np.exp(ppl)@np.exp(arr))).round(2)
# print(res)
res = np.exp((ppl@arr)).round(2)
print(res)
res = (ppl@arr).round(2)
print(res)


arr
[ 0.208  0.715 -1.711]
ppl
[[1.08856195 4.44265126 0.        ]
 [2.34660198 4.09434456 0.        ]
 [1.34807315 4.65396035 0.        ]]
[30.05 30.43 36.89]
[3.4  3.42 3.61]
