In [66]:
# import pandas as pd
import numpy as np
# import io
import statsmodels.formula.api as smf
import statsmodels.api as sm
# import scipy.stats as stats
import re

In [67]:
data_str = '''log(capital)                 0.183***          
                              (0.017)          
                                               
log(labour)                  0.515***          
                              (0.083)          
                                               
I(log(capital)2)             0.023***          
                              (0.005)          
                                               
I(log(labour)2)               0.020**          
                              (0.010)          
                                               
Constant                     -1.304***         
                              (0.189)   '''

In [68]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_data = re.findall(r'([-+]?\d+.\d+)',data_str)
digital_data

['0.183',
 '0.017',
 '0.515',
 '0.083',
 '0.023',
 '0.005',
 '0.020',
 '0.010',
 '-1.304',
 '0.189']

In [69]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 8 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
arr = np.reshape(digital_data,(5,2))
# Удаляем последнюю строчку (она нам не понадобится)
# arr = np.delete(arr, 2, 0)
# Убираем последний столбец, он тоже не нужен
arr = arr[:, 0]
# Переводим строки в вещественные числа
arr = arr.astype(float)
arr

array([ 0.183,  0.515,  0.023,  0.02 , -1.304])

In [70]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''  capital labour
                ----------------
                1  22.140   407  
                2  7.320   197  
                3  0.670    31  '''

In [71]:
# Создадим список из чисел, содержащихся в строке. 
# ppl_list -- список, который будет состоять из подстрок, каждая из которых удовлетворяет определенному шаблону символов
# ppl_lst = re.findall(r'([-+]?\d+.\d+|[-+]?\d+)',ppl_string)
ppl_lst = re.findall(r'(\d+.\d+|\d+)',ppl_string)
ppl_lst

['1', '22.140', '407', '2', '7.320', '197', '3', '0.670', '31']

In [72]:
ppl = np.reshape(ppl_lst,(3,3))
ppl

array([['1', '22.140', '407'],
       ['2', '7.320', '197'],
       ['3', '0.670', '31']], dtype='<U6')

In [73]:
# Убираем колонку с нумерацией строк
ppl = np.delete(ppl,0,1)
# Теперь необходимо добавить столбец из единиц для того,
#  чтобы совпадало количество столбцов в матрице с количестом элементов 
ppl = np.c_[ppl,np.ones(3)]
ppl

array([['22.140', '407', '1.0'],
       ['7.320', '197', '1.0'],
       ['0.670', '31', '1.0']], dtype='<U32')

In [74]:
ppl.shape

(3, 3)

In [75]:
arr.shape

(5,)

In [76]:
# arr = arr.astype(float)
ppl =ppl.astype(float)
# Вставляем квадрат значения capital в третью колонку
ppl = np.insert(ppl, 2 , ppl[:,0]**2, axis= 1)
# Вставляем квадрат значения labour в четвертую колонку
ppl = np.insert(ppl, 3 , ppl[:,1]**2, axis= 1)
ppl

array([[2.214000e+01, 4.070000e+02, 4.901796e+02, 1.656490e+05,
        1.000000e+00],
       [7.320000e+00, 1.970000e+02, 5.358240e+01, 3.880900e+04,
        1.000000e+00],
       [6.700000e-01, 3.100000e+01, 4.489000e-01, 9.610000e+02,
        1.000000e+00]])

In [77]:
ppl.shape

(3, 5)

In [78]:
ppl = np.log(ppl)
# arr = np.exp(arr)

In [79]:
# print('arr')
# print(arr)
# print('ppl')
# print(ppl)
# res = ((np.exp(ppl)@np.exp(arr))).round(2)
# print(res)
# res = np.exp((ppl@arr)).round(2)
# print(res)
res = (ppl@arr).round(2)
print(res)


[4.04 3.39 1.81]
