In [513]:
# import pandas as pd
import numpy as np
# import io
import statsmodels.formula.api as smf
import statsmodels.api as sm
# import scipy.stats as stats
import re

In [514]:
data_str = '''log(capital)                 0.208***          
                              (0.017)          
                                               
log(labour)                  0.715***          
                              (0.023)          
                                               
Constant                     -1.711***         
                              (0.097)'''

In [515]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_data = re.findall(r'([-+]?\d+.\d+)',data_str)
digital_data

['0.208', '0.017', '0.715', '0.023', '-1.711', '0.097']

In [516]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 3 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
beta = np.reshape(digital_data,(3,2))
# Удаляем последнюю строчку (она нам не понадобится)
# beta = np.delete(beta, 2, 0)
# Убираем последний столбец, он тоже не нужен
beta = beta[:, 0]
# Переводим строки в вещественные числа
beta = beta.astype(float)
# beta = np.insert(beta, 0, 1)
# beta = np.delete(beta, 3, 0)
# beta = np.log(beta)
# beta = np.exp(beta)
beta

array([ 0.208,  0.715, -1.711])

In [517]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''capital labour
                ----------------
                1  2.970    85  
                2  10.450    60  
                3  3.850   105  '''

In [518]:
# Создадим список из чисел, содержащихся в строке. 
# ppl_list -- список, который будет состоять из подстрок, каждая из которых удовлетворяет определенному шаблону символов
# ppl_lst = re.findall(r'([-+]?\d+.\d+|[-+]?\d+)',ppl_string)
X = re.findall(r'(\d+.\d+|\d+)',ppl_string)
X

['1', '2.970', '85', '2', '10.450', '60', '3', '3.850', '105']

In [519]:
X = np.reshape(X,(3,3))
X

array([['1', '2.970', '85'],
       ['2', '10.450', '60'],
       ['3', '3.850', '105']], dtype='<U6')

In [520]:
# Теперь необходимо добавить столбец из единиц для того,
#  чтобы совпадало количество столбцов в матрице с количестом элементов 
X = np.delete(X,0,1)
# X = np.c_[X,np.ones(3)]
# X = np.insert(X, 0 , '1', axis= 1)
# X = np.c_[X,np.ones(3)]
# X = np.insert (X, 3 , np.ones(3), axis= 1 )
X

array([['2.970', '85'],
       ['10.450', '60'],
       ['3.850', '105']], dtype='<U6')

In [521]:
X.shape

(3, 2)

In [522]:
beta.shape

(3,)

In [523]:
# arr = arr.astype(float)
X = X.astype(float)
X = np.log(X)
# X = np.insert(X, 0 , 1, axis= 1)
X = sm.add_constant(X)
X

array([[1.        , 1.08856195, 4.44265126],
       [1.        , 2.34660198, 4.09434456],
       [1.        , 1.34807315, 4.65396035]])

In [524]:
output_eq2 = sm.OLS(beta, X).fit()
output_eq2.params


array([33.67242489, -1.57559738, -7.14647351])

In [527]:
rep = output_eq2.params
print(type(output_eq2))
print(rep)
np.exp(output_eq2.predict(exog=X, transform=False))

<class 'statsmodels.regression.linear_model.RegressionResultsWrapper'>
[33.67242489 -1.57559738 -7.14647351]


array([1.23121317, 2.04418668, 0.18068502])

In [526]:
# print('X')
# print(X)
# print('beta')
# print(beta)
# res = ((np.exp(beta)@np.exp(X))).round(2)
# print(res)
# res = np.exp((beta@X)).round(2)
# res = np.exp((X@beta)).round(2)
# print(res)
# res = (X@beta).round(2)
# print(res)
