# Задача 1.1

In [1]:
import numpy as np
import re

In [10]:
data_string = '''totwrk                       -0.169***         
                              (0.018)          
                                               
age                           2.689*           
                              (1.469)          
                                               
south                        101.568**         
                             (41.837)          
                                               
male                         87.669**          
                             (35.104)          
                                               
smsa                         -54.748*          
                             (33.123)          
                                               
yngkid                        -13.962          
                             (50.341)          
                                               
marr                          31.211           
                             (42.233)          
                                               
Constant                    3450.913***        
                             (80.726)'''
data_string

'totwrk                       -0.169***         \n                              (0.018)          \n                                               \nage                           2.689*           \n                              (1.469)          \n                                               \nsouth                        101.568**         \n                             (41.837)          \n                                               \nmale                         87.669**          \n                             (35.104)          \n                                               \nsmsa                         -54.748*          \n                             (33.123)          \n                                               \nyngkid                        -13.962          \n                             (50.341)          \n                                               \nmarr                          31.211           \n                             (42.233)          \n                   

In [11]:
data_num = re.findall(r'([-+]?\d+.\d+)',data_string)
data_num

['-0.169',
 '0.018',
 '2.689',
 '1.469',
 '101.568',
 '41.837',
 '87.669',
 '35.104',
 '-54.748',
 '33.123',
 '-13.962',
 '50.341',
 '31.211',
 '42.233',
 '3450.913',
 '80.726']

In [13]:
beta = np.reshape(data_num,(8,2))
beta

array([['-0.169', '0.018'],
       ['2.689', '1.469'],
       ['101.568', '41.837'],
       ['87.669', '35.104'],
       ['-54.748', '33.123'],
       ['-13.962', '50.341'],
       ['31.211', '42.233'],
       ['3450.913', '80.726']], dtype='<U8')

In [16]:
beta[:,0]

array([-1.690000e-01,  2.689000e+00,  1.015680e+02,  8.766900e+01,
       -5.474800e+01, -1.396200e+01,  3.121100e+01,  3.450913e+03])

In [18]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''totwrk age south male smsa yngkid marr
----------------------------------------
1  2150  37    0    1    1     0     1  
2  1950  28    1    1    0     1     0  
3  2240  26    0    0    1     0     0 '''

In [19]:
ppl_lst = re.findall(r'([-+]?\d+)', ppl_string)
ppl_lst

['1',
 '2150',
 '37',
 '0',
 '1',
 '1',
 '0',
 '1',
 '2',
 '1950',
 '28',
 '1',
 '1',
 '0',
 '1',
 '0',
 '3',
 '2240',
 '26',
 '0',
 '0',
 '1',
 '0',
 '0']

In [22]:
ppl_numb = np.reshape(ppl_lst,(3,8))
ppl_numb

array([['1', '2150', '37', '0', '1', '1', '0', '1'],
       ['2', '1950', '28', '1', '1', '0', '1', '0'],
       ['3', '2240', '26', '0', '0', '1', '0', '0']], dtype='<U4')

In [23]:
ppl_numb = np.delete(ppl_numb,0,1)
ppl_numb

array([['2150', '37', '0', '1', '1', '0', '1'],
       ['1950', '28', '1', '1', '0', '1', '0'],
       ['2240', '26', '0', '0', '1', '0', '0']], dtype='<U4')

In [24]:
ppl_numb = np.c_[ppl_numb,np.ones(3)]
ppl_numb

array([['2150', '37', '0', '1', '1', '0', '1', '1.0'],
       ['1950', '28', '1', '1', '0', '1', '0', '1.0'],
       ['2240', '26', '0', '0', '1', '0', '0', '1.0']], dtype='<U32')

In [25]:
beta = beta.astype(float)
ppl_numb = ppl_numb.astype(float)

In [26]:
beta

array([[-1.690000e-01,  1.800000e-02],
       [ 2.689000e+00,  1.469000e+00],
       [ 1.015680e+02,  4.183700e+01],
       [ 8.766900e+01,  3.510400e+01],
       [-5.474800e+01,  3.312300e+01],
       [-1.396200e+01,  5.034100e+01],
       [ 3.121100e+01,  4.223300e+01],
       [ 3.450913e+03,  8.072600e+01]])

In [27]:
ppl_numb

array([[2.15e+03, 3.70e+01, 0.00e+00, 1.00e+00, 1.00e+00, 0.00e+00,
        1.00e+00, 1.00e+00],
       [1.95e+03, 2.80e+01, 1.00e+00, 1.00e+00, 0.00e+00, 1.00e+00,
        0.00e+00, 1.00e+00],
       [2.24e+03, 2.60e+01, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
        0.00e+00, 1.00e+00]])

In [28]:
ppl_numb@beta[:,0]

array([3251.188, 3371.93 , 3087.519])

In [29]:
beta[:,1]

array([1.8000e-02, 1.4690e+00, 4.1837e+01, 3.5104e+01, 3.3123e+01,
       5.0341e+01, 4.2233e+01, 8.0726e+01])

# Лист 8

## Задание 1.1

In [30]:
import pandas as pd
import numpy as np
import statsmodels.api as sm 
import statsmodels.formula.api as smf
from statsmodels.iolib.summary2 import summary_params # вывод результатов тестирования
from statsmodels.iolib.summary2 import summary_col # вывод результатов тестирования
from statsmodels.stats.outliers_influence import variance_inflation_factor # VIF
import scipy
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df['totwrk2_10000'] = df['totwrk']**2/10000

In [40]:
model = smf.ols(data = df , formula = 'sleep~I(totwrk/100)+totwrk2_10000 +  age + smsa + male + south').fit()
model_1 = smf.ols(data = df , formula = 'I(totwrk/100)~totwrk2_10000 +  age + smsa + male + south').fit()
model_2 = smf.ols(data = df , formula = 'totwrk2_10000~ I(totwrk/100)+  age + smsa + male + south').fit()
model_3 = smf.ols(data = df , formula = 'male~totwrk2_10000+ I(totwrk/100)+  age + smsa  + south').fit()
model_1.params.round(3)

Intercept        9.003
totwrk2_10000    0.021
age             -0.008
smsa             0.357
male             1.071
south            0.989
dtype: float64

In [44]:
model_1.rsquared

0.8820765217832193

In [46]:
VIF_1 = 1/(1 - model_1.rsquared.round(3))
VIF_1.round(2)

8.47

In [49]:
VIF_2 = 1/(1 - model_2.rsquared.round(3))
VIF_2.round(2)

8.26

In [50]:
VIF_3 = 1/(1 - model_3.rsquared.round(3))
VIF_3.round(2)

1.17

## Задача 1.2

In [52]:
# Модель sleep на totwrk/100, totwrk^2/10000, age, smsa, male
Sleep_eq12 = smf.ols(formula = 'sleep~I(totwrk/100)+I(totwrk**2/10000)+age+smsa+male', data = data_sleep).fit()

In [53]:
info_dict = {'No. Observations': lambda x: '{0:d}'.format(int(x.nobs)), 
             'Residual Std. Error': lambda x: "%#8.3f" % x.mse_resid**0.5,
             'F-statistic': lambda x: '{:.3f}'.format(x.fvalue), 
             'Prob (F-statistic)': lambda x: '{:.3f}'.format(x.f_pvalue)
             }
print(summary_col(Sleep_eq12, float_format='%.3f', stars=True, info_dict = info_dict))


                          sleep   
----------------------------------
Intercept              3428.805***
                       (76.655)   
I(totwrk / 100)        -8.195*    
                       (4.789)    
I(totwrk ** 2 / 10000) -0.214*    
                       (0.111)    
age                    2.817**    
                       (1.387)    
smsa                   -78.049**  
                       (32.072)   
male                   86.639**   
                       (34.200)   
R-squared              0.128      
R-squared Adj.         0.122      
No. Observations       706        
Residual Std. Error    416.457    
F-statistic            20.566     
Prob (F-statistic)     0.000      
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01


In [54]:
df = summary_params(Sleep_eq12, alpha=0.05)
df['significance'] = df.apply(lambda x: 'Значим' if x['P>|t|']<0.05 else 'Незначим', axis=1)
df

Coef.   Std.Err.          t          P>|t|  \
Intercept               3428.804849  76.655048  44.730320  2.023213e-207   
I(totwrk / 100)           -8.195316   4.789446  -1.711120   8.750201e-02   
I(totwrk ** 2 / 10000)    -0.214156   0.110951  -1.930194   5.398646e-02   
age                        2.816697   1.386926   2.030892   4.264340e-02   
smsa                     -78.049460  32.072351  -2.433543   1.520105e-02   
male                      86.638759  34.199952   2.533301   1.151657e-02   

                             [0.025       0.975] significance  
Intercept               3278.303493  3579.306204       Значим  
I(totwrk / 100)          -17.598716     1.208085     Незначим  
I(totwrk ** 2 / 10000)    -0.431992     0.003680     Незначим  
age                        0.093663     5.539731       Значим  
smsa                    -141.018991   -15.079930       Значим  
male                      19.491986   153.785532       Значим